# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('vimarsh18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
