# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='choice',
            field=models.CharField(default='no choice', max_length=100),
            preserve_default=False,
        ),
    ]
