# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0003_participant_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='pay_mode',
            field=models.CharField(default='pay_venue', max_length=20),
        ),
    ]
