# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0004_participant_pay_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='choice',
            field=models.CharField(max_length=200),
        ),
    ]
