# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('vimarsh18', '0005_auto_20181002_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_code_reg',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ImageField(upload_to='qr_codes')),
            ],
        ),
    ]
