# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0006_qr_code_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code_reg',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes'),
        ),
    ]
