# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0007_auto_20181004_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', imagekit.models.fields.ProcessedImageField(upload_to='vimarsh18_speakers')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('info', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
