# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0008_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_vim',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=2)),
                ('domain', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
