# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0010_id_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['name']},
        ),
    ]
