# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0012_auto_20181015_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session_vim',
            options={'ordering': ['day', 'start_time', 'end_time']},
        ),
        migrations.AlterField(
            model_name='session_vim',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
