# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimarsh18', '0016_auto_20181015_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_img', models.ImageField(null=True, upload_to='id_cards_special')),
            ],
        ),
    ]
