# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_list_yuva',
            fields=[
                ('college_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='user_check',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_confirmation_status', models.BooleanField(default=False)),
                ('profile_status', models.BooleanField(default=False)),
                ('manager_status', models.BooleanField(default=False)),
            ],
        ),
    ]
