# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_check',
            name='profession',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
