# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0003_user_check_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
