# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_other_info_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_check',
            name='reciept_manager_status',
            field=models.BooleanField(default=False),
        ),
    ]
