# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_check_reciept_manager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='course',
            field=models.CharField(max_length=60),
        ),
    ]
