# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='up_events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', imagekit.models.fields.ProcessedImageField(upload_to='upcoming_events')),
                ('name', models.CharField(max_length=100)),
                ('short_info', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=200)),
                ('poc_name', models.CharField(max_length=100)),
                ('poc_number', models.CharField(max_length=100)),
                ('fb_link', models.CharField(max_length=200)),
            ],
        ),
    ]
