# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_dashboard', '0002_auto_20180822_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_events',
            name='to_post',
            field=models.BooleanField(default=False),
        ),
    ]
