# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_dashboard', '0003_up_events_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='up_events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
