# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_dashboard', '0004_auto_20180826_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='up_events',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
