# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_dashboard', '0005_auto_20180826_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_events',
            name='fb_link_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='up_events',
            name='reg_link',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='up_events',
            name='reg_link_status',
            field=models.BooleanField(default=False),
        ),
    ]
