# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_dashboard', '0006_auto_20180902_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='vimarsh18_reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciept_manager', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reciept_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
